### ISSUE TITLE
rev_news: try out the new github pages feed thing

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#101]
Ref https://github.com/blog/2053-easier-feeds-for-github-pages

This could make our RSS feed more usable. I haven't heard any complaints yet, but just in case someone wants to have a go at this..

**Comment by dscho** [comment]
You probably want to mark this as "Up For Grabs" or something like that. Or close it.

**Comment by tfnico** [comment]
Yeah, no point in using open issues for ideas we might never get around to.
