### ISSUE TITLE
Gmane bugs and outages

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#114]
I spend a lot of time these days to try to overcome gmane bugs or outages.

This is a problem because until now we have been using mostly gmane links especially for links from article titles to the discussion thread.

The last problem I had yesterday with gmane is that the following thread is missing some messages:

http://thread.gmane.org/gmane.comp.version-control.git/281254/

For example it is missing this message:

http://article.gmane.org/gmane.comp.version-control.git/281323/

I would have liked to write an article about this thread, but I didn't want to use a link to a broken thread on gmane, so I eventually chose another thread to write about.

**Comment by chriscool** [comment]
By the way if one wants the thread associated with the above link, that is:

http://thread.gmane.org/gmane.comp.version-control.git/281323/

One gets:

> Error GMANE-03252: Something is wrong. Perhaps something didn't match a group name. Perhaps something else.

**Comment by tfnico** [comment]
@chriscool do you think it would be more stable to use http://www.spinics.net/lists/git/ or http://marc.info/?l=git (the latter one is actually not responding to my request atm).

**Comment by chriscool** [comment]
@tfnico I am not sure it will be more stable, but I think we will probably have to start using those, yeah.
I will see next time I have a problem.

cc @larsmagne

**Comment by mhagger** [comment]
Are you aware of Gmane's interface to search for messages by Message-ID?

    http://mid.gmane.org/%s

Using this kind of link in the newsletter would have the big advantage that the Message-ID can be mapped to a unique mailing list message independent of the Gmane service. So if Gmane becomes temporarily (or permanently!) unavailable, one could extract the Message-IDs from these URLs and map them to URLs on other mailing list archives.

Therefore, it might be prudent to use Message-ID-based URLs for links in the newsletter, or at least to record the Message-IDs somewhere for the permanent record, to reduce the dependence on Gmane.

I am not aware if Gmane has corresponding URLs for the email thread containing a given message. That could be a flaw in this suggestion.

**Comment by peff** [comment]
> I am not aware if Gmane has corresponding URLs for the email thread containing a given message.

I think you want `http://news.gmane.org/find-root.php?message_id=...` ([example](http://news.gmane.org/find-root.php?message_id=20151210213228.GB29055%40sigill.intra.peff.net)).

**Comment by chriscool** [comment]
@mhagger and @peff, yeah these are good suggestions. I will try to use such kind of links in the next edition.
Thanks!

**Comment by gitster** [comment]
Have you contacted http://gmane.org/contact.php and let Lars know about the problem? He's been quite helpful.

**Comment by chriscool** [comment]
I have cc'ed him above, but yeah I will email him if there are problems again.

**Comment by chriscool** [comment]
So let's close this one. We can open it again if there are problems again.

**Comment by chriscool** [comment]
Ok, so it looks like there are problems again...

**Comment by chriscool** [comment]
As the Git mailing list now uses [Public Inbox](https://public-inbox.org/git/), let's use that too.

**Comment by tfnico** [comment]
@chriscool sounds good. Public Inbox looks cool for many reasons. +1 for closing this one again.

**Comment by chriscool** [comment]
Ok, let's close this one again.
