### ISSUE TITLE
Broken links all around

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#141]
It seems at some point the Jekyll/GitHub Pages thingie broke our links. Basically everywhere where we link to something rev_news/rev_news.html, it breaks on GitHub, but not when running locally with Jekyll. I'm not sure if this is a configuration issue, or some limitation in GitHub pages, but it's too late in the evening for me to fiddle with it now. Will have a look another day.

**Comment by chriscool** [comment]
Yeah, it is strange because http://git.github.io/rev_news/ works.
Maybe we can replace "rev_news/rev_news.html" with just "rev_news/" everywhere.

**Comment by chriscool** [comment]
I mean replace "rev_news/rev_news.html" with "rev_news/rev_news/" everywhere.
I started doing that...

**Comment by chriscool** [comment]
Ok, I think I fixed everything.

**Comment by tfnico** [comment]
Thanks, Chris. I'll close this for now. Would've been nice to have backward-compatible URLs, but I don't have time to look into it.
