### ISSUE TITLE
rev_news: Broken rendering in edition 5

### ISSUE THREAD

**Issue by dpursehouse** [git/git.github.io#149]
It looks like there's something wrong with the markdown in [edition 5](https://git.github.io/rev_news/2015/07/08/edition-5/).  More than half the page is being rendered as raw text.

(Search for "creates a new branch" to find the start of the raw text).

**Comment by moy** [comment]
Strange, the markdown seems correct and is rendered properly on https://github.com/git/git.github.io/blob/master/_posts/2015-07-08-edition-5.markdown.

**Comment by chriscool** [comment]
Ok, I commited https://github.com/git/git.github.io/commit/e7ef89c656f22b60e4d86b976edd66cd35f3b574 and it looks like it is fixed.

**Comment by dpursehouse** [comment]
Thanks.  Confirmed it's now rendering correctly.
