### ISSUE TITLE
https on git.github.io

### ISSUE THREAD

**Issue by peff** [git/git.github.io#158]
GitHub Pages now [officially support https](https://github.com/blog/2186-https-for-github-pages), and we can start using to `https://` links everywhere. We should probably mass-update existing links to use `https`.

Likewise, there's now a config option we can flip to redirect `http` traffic to `https` automatically. I can't think of a good reason _not_ to do this, unless there's somebody who really has an http implementation that can't do https.  That seems far-fetched to me in 2016. So modulo any objections, I'll do that soon in a day or two.

/cc @git/web

**Comment by chriscool** [comment]
Ok for me. Thanks!

**Comment by peff** [comment]
OK, switch is flipped. I also opened #159 to mass-convert the links.

**Comment by chriscool** [comment]
Great! Everything seems to work well on the Git Rev News side.
