### ISSUE TITLE
Project or microproject ideas for next GSoC or Outreachy

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#188]
Not sure it's the best place to store and discuss some ideas, but anyway here are a few:
- `git log --oneline` improvements as discussed in https://public-inbox.org/git/xmqqeg42fslw.fsf@gitster.mtv.corp.google.com/T/#t
- improvements to `git name-rev` or `git for-each-ref` or `git log --stdin --no-walk` or `git cat-file --batch-check` to better format object related information as discussed in https://public-inbox.org/git/CA+P7+xr4ZNCCJkS0=yR-FNu+MrL60YX-+Wsz9L_5LCNhnY_d=A@mail.gmail.com/

**Comment by peff** [comment]
I don't think this issue is a good place to discuss (it just doesn't get as much visibility as the list), but I agree those are reasonable project areas.

No objection to adding them to the list for now as reminders, and then we can discuss and expand the list when GSoC gets closer (or now, if people are interested).

**Comment by chriscool** [comment]
I am a bit reluctant to add them to the list of 2016 ideas, as the 2016 GSoC is over and I think it could confuse people if we change the 2016 list afterwards. As we would have to move them to the 2017 list anyway, I wonder if we could just start the 2017 list with them.

**Comment by chriscool** [comment]
Another obvious idea is:

- Move toward an interactive rebase fully in C as described [in @dscho 's answer to @jnareb](http://public-inbox.org/git/alpine.DEB.2.20.1609021432070.129229@virtualbox/)

**Comment by peff** [comment]
Yes, it's a great idea to start the 2017 list now. Sooner is better, if it provides a space for people to collect and refine ideas.

**Comment by chriscool** [comment]
Closing as PR #189 as been merged.
