### ISSUE TITLE
Allow “-“ as a short-hand for “@{-1}” in more places

### ISSUE THREAD

**Issue by PhilipOakley** [git/git.github.io#234]
This is listed as a possible microproject, but it looks like its well in progress if I read the list correctly. Is it still a valid microproject?

**Comment by chriscool** [comment]
@PhilipOakley You should probably ask this on the mailing list as I am not sure about what is going on on this, and few people look at issues here.
Maybe you could ask on the most recent thread started by student interested in this microproject.

**Comment by chriscool** [comment]
In fact it has been removed a few days ago by Junio see PR https://github.com/git/git.github.io/pull/235, so I am closing this.
