### ISSUE TITLE
Any comment about current Git Rev News edition 28

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#246]
A currently mostly empty draft is there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-28.md

Feel free to comment in this issue, or to use the edit button (that looks like a pen) to edit and create a pull request with the changes you would like.

Thanks!

cc @tfnico @jnareb @mjaix @gitster

**Comment by stefanbeller** [comment]
Maybe include the article http://sdtimes.com/giter-done-scm-system-keeps-developers-projects-track/

**Comment by chriscool** [comment]
Let's try to publish this edition next Wednesday (June 14th)!

**Comment by chriscool** [comment]
@stefanbeller done in https://github.com/git/git.github.io/commit/287f27b7e99e9a4b71453239429652ed902106dc

**Comment by jnareb** [comment]
A few more links in 6e61405171

**Comment by mjaix** [comment]
Hi,

typo fixing was almost unnecessary this time, so I deliberately
inserted Brandon Williams' spotlight section.

Cheers,
Markus

**Comment by tfnico** [comment]
Just pushed some added links and releases.

**Comment by jnareb** [comment]
@tfnico Should we unify formatting of releases?

**Comment by jnareb** [comment]
New pull request #250 - because I am not sure if it is good or not

**Comment by chriscool** [comment]
This edition has been published last month.
