### ISSUE TITLE
A new Magit (git client) release is out and a fundraising campaign is in progress

### ISSUE THREAD

**Issue by tarsius** [git/git.github.io#258]
Could you please consider including some information about Magit in the next revision?

Magit is a Git user interface that is implemented as an Emacs package. It is very popular among Emacs users and often considered to be one of its killer features. I am currently running a Kickstarter campaign to support my work for a year. One of the goals is to make it more accessible to non-Emacs users. Many of the articles that I have published when I launched the campaign are specifically for non-Emacs users.

Thanks!

* Homepage https://magit.vc
* Kickstarter https://www.kickstarter.com/projects/1681258897/its-magit-the-magical-git-client
* Articles https://emacsair.me/2017/09/01/campaign-articles
* Release https://emacsair.me/2017/09/13/magit-2.11/

**Comment by tfnico** [comment]
@tarsius Of course! Thanks for the tip :)

**Comment by tarsius** [comment]
Thanks!

Do you already have an idea when you will publish? Of course I hope that will be before the end of my campaign, but some publicity would be useful after that as well.

**Comment by tfnico** [comment]
My guess would be that the next edition will go out next week Wednesday, right @chriscool ?

I just did some tweeting from my private account to help you along ;)

**Comment by tarsius** [comment]
> My guess would be that the next edition will go out next week Wednesday

I asked because there was no content in the draft. But later I saw that that often isn't inserted shortly before publishing.

> I just did some tweeting from my private account to help you along ;)

Thanks! I saw that. You've been retweeted ;-)

**Comment by chriscool** [comment]
> My guess would be that the next edition will go out next week Wednesday, right @chriscool ?
Yeah, that's the plan. And sure I am ok with including information about Magit.

**Comment by chriscool** [comment]
@tarsius please take a look at the current draft:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-31.md

to see how your info about Magit will look like.

**Comment by tarsius** [comment]
Looks good. Thanks!

I am under the impression that despite my efforts I could not interest many non-Emacs users so far (but I don't really have any reliable data). That might be partially due to the crappy video, so I am planning to replace that. Just so that I know how much I have to hurry with that - are still planning on publishing on Wednesday? Also, would you mind appending `?ref=bnkptt` to the Kickstarter url?

**Comment by chriscool** [comment]
@tarsius yeah, we are still planning on publishing on Wednesday, and ok I just changed the Kickstarter url.

**Comment by tarsius** [comment]
Thanks!

**Comment by chriscool** [comment]
@tarsius by the way you may also want to send an email directly to the mailing list. I don't think people will object or consider it spam.

**Comment by tarsius** [comment]
Oh, thanks for the hint!
