### ISSUE TITLE
RSS feed for Git Rev News

### ISSUE THREAD

**Issue by alexeyr** [git/git.github.io#30]
It would be nice to have an RSS feed for Git Rev News.

**Comment by tfnico** [comment]
Thanks for posting this issue. This will surely come into existence at some point, as long as everyone involved are happy to continue the effort.

Another vote from a Google+ [comment](https://plus.google.com/u/0/+ThomasFerrisNicolaisen/posts/gQVCaBcnqBr):
```
Nice! Is there actually a way to subscribe to this news 
letter, e.g. by RSS / Atom feed? I'd prefer that over 
subscribing to some mailing list.﻿
```

**Comment by gasche** [comment]
I came to post this same issue. I won't be able to keep track of Git Rev News unless there is a feed available, so that I can be notified of new posts instead of having to check it regularly (a mailing-list would work as well).

**Comment by chriscool** [comment]
Maybe we could ask people who maintain http://gitrss.q42.co.uk/ to add a feed for Git Rev News?

**Comment by tfnico** [comment]
As soon as we have Jekyll up and going, we should have RSS feeds generated. Ref discussion in #29.

**Comment by chriscool** [comment]
@tfnico yeah, ok let's see if we can generate RSS feeds using Jekyll first.

**Comment by drorata** [comment]
:+1: RSS is a most have. Thanks for the efforts!

**Comment by tfnico** [comment]
Fiddled around with my Ruby environment now for an hour and at least managed to get the current Jekyll site running locally. I'll try out making some RSS feeds the coming week.

**Comment by chriscool** [comment]
@tfnico great, thanks!

**Comment by tfnico** [comment]
I've got quick attempt going on https://github.com/tfnico/git.github.io/commit/494dff98ba7c426ae60dadfe355197533bbcafc0
if anyone wants to try it out. The RSS feed is there, but still some rough edges.

**Comment by chriscool** [comment]
Ok, I will try it this hopefully evening! Thanks!

**Comment by chriscool** [comment]
@tfnico thanks, it looks good!
It's also very nice that you describe how to install everything needed to make it work!
We need to fix the problems you describe in your commit and also try to improve the look.
I will have a look at that soon.

**Comment by tfnico** [comment]
@chriscool Glad you got it running locally too. We have to be careful not to spend too much time on design and looks though, that can be a big time-sink.

My top priorities before merging and shipping this would be:

- [ ] Don't break any old URLs
  - [ ] http://git.github.io/rev_news/rev_news.html should stay as it is today (About Rev News)
  - [ ] http://git.github.io/rev_news/[index.html] should be where we iterate over posts
  - [ ] http://git.github.io/rev_news/edition-1.html should redirect to new permalink scheme
- [ ] Get new posts permalink scheme working (rev_news/date/title or something like that)
- [ ] Get rid of the empty bullets in the nav-menu
- [ ] Show the old About Rev News content on a dedicated page
- [ ] Add RSS link on the About page

**Comment by chriscool** [comment]
@tfnico yeah I agree that we should not spend too much time on this.

And I agree with your priorities before merging and shipping, except that I don't understand why there is "Show the old About Rev News content on a dedicated page". It looks incompatible with "http://git.github.io/rev_news/rev_news.html should stay as it is today (About Rev News)".

Thanks!

**Comment by tfnico** [comment]
@chriscool I gave it another push, please have a look now: https://github.com/tfnico/git.github.io/commit/f29974c6e9bd62a2c64429127078c483851ff15f

I've checked off the corresponding points in the above checklist.

**Comment by tfnico** [comment]
@chriscool I managed to get rid of one empty bullet in the nav-menu by setting navbar: false in the feed.xml page: https://github.com/tfnico/git.github.io/commit/cc573aa37bc253e833ff05954831f8d0f68eb15c

There's one more empty bullet, but I'll have to bisect a bit further back to find out where it's coming from.

**Comment by tfnico** [comment]
OK, the last empty bullet stems from the redirect_from plugin thingie introduced in 95756224aa1c.

The redirect_from will generate a dummy page, which has no navbar:false, and is thus included in the navbars iteration of site.pages. 

So I don't know any "easy" way of getting rid of it, except maybe inverting the logic for what appears in the navbar (require navbar:true for all pages we want to appear in the navbar). We could just leave it for now and merge with that one remaining empty bullet point.

**Comment by chriscool** [comment]
@tfnico thanks! I will have a look at the result soon.

About the last empty bullet and the redirect_from, what do you think about Peff's suggestion "it would make more sense to have an index at the rev_news/ root rather than a redirect" (https://github.com/git/git.github.io/commit/95756224aa1cb03b96c99a0850da77961351beeb)?

Thanks again!

**Comment by chriscool** [comment]
cc @peff

**Comment by tfnico** [comment]
@chriscool I already have that index at the root of rev_news/ now: https://github.com/tfnico/git.github.io/blob/master/rev_news/index.md

So we already have implemented Peff's "obvious alternative". 

The problem remains because I want to keep the URL http://git.github.io/rev_news/edition-1.html alive and well. The new URL (with Jekyll's permalink scheme) to the first edition is http://git.github.io/rev_news/2015-03-25-edition-1/ or something like that.

Hence, I've done a new redirect in https://github.com/tfnico/git.github.io/blob/master/_posts/2015-03-25-edition-1.markdown to send people from the old URL to the new one.

**Comment by tfnico** [comment]
@chriscool OK, I worked around it with duplication the first edition post: https://github.com/tfnico/git.github.io/commit/31c1a03978f869419d0e2d5d13e81fd6c0a8a200

It's not pretty, but better than what we have live now. Good to merge, you think?

**Comment by chriscool** [comment]
@tfnico yeah, as I wrote on the pull request it is great!
As the PR is merged, I am closing this issue.
Thanks a lot!

**Comment by chriscool** [comment]
Just for reference the RSS feed is: http://git.github.io/feed.xml
