### ISSUE TITLE
Mailing list for Rev News

### ISSUE THREAD

**Issue by Cogito** [git/git.github.io#31]
It would be useful for people interested in this publication to be able to subscribe to it via email.

There was some interest shown on hacker news - https://news.ycombinator.com/item?id=9264924

At the very least, letting people know how they can get new issues when they are released is important, even better if they can sign up to a list while reading an issue.

**Comment by tfnico** [comment]
Thanks for posting this issue. This relates a bit to #30, but a mailing list is somewhat a different animal. The only idea off the top of my head would be to copy paste the editions into a service like MailChimp for starters, but I have no idea whether that is the best approach. We could also start a dedicated Google Group whose purpose it is only to be posted with these news letters. 

CC @chriscool

**Comment by Cogito** [comment]
Yes, I saw #30 but thought it probably deserved its own issue. The main thing is that at the moment the only way to here about the issue is through the dev list. I'm sure that will change in some way as this matures!

**Comment by wking** [comment]
You can convert an RSS/Atom feed to mail automatically with [rss2email][1] (which I maintain).  So folks interested in getting email announcements could run rss2email locally.  Alternatively, someone could setup a public mailing list and use rss2email to automatically feed entries into the list.  Until someone tackles #30, I'll just be “Watching” this repository on GitHub, and having them send me notification email ;).

[1]: https://github.com/wking/rss2email

**Comment by chriscool** [comment]
@wking thanks for telling us about rss2email. 

Another solution might be to use [ANNOUNCE] when we post about a new Git Rev News edition on the list and then ask people who want to be notified to subscribe to this announce only list: 

http://lists.q42.co.uk/listinfo/git-announce

Or maybe we can ask people who maintain this list if they could create a specific list for Git Rev News.

**Comment by Cogito** [comment]
Whatever the preferred method (and I would suggest the simplest for users) the main thing will be to include instructions each release.

I would definitely prefer to read the content in my email client vs clicking through a link, not sure if that would effect the structure or styling of the content.

**Comment by chriscool** [comment]
Thanks to @tfnico issue #30 (RSS feed for Git Rev News) is now closed and the RSS feed is there:  http://git.github.io/feed.xml

Not sure if it is better to find a way to use https://github.com/wking/rss2email or if it is better to ask people running http://lists.q42.co.uk/listinfo/git-announce.

@tfnico do you have an opinion on this? Maybe we can discuss it at the Git Merge next week?

**Comment by tfnico** [comment]
@chriscool My thoughts are pretty much:

The easiest and most user friendly option is to use MailChimp or a similar service. Unfortunately, their free tier ends at 2000 subscribers, which I think we'll exhaust in a year or so if Rev News is successful.

The most reliable free option I think is Google Groups. It is the most used mailing list service out there, at least in the open source world, and while it usually functions as a forum, it also can serve as a platform for newsletters. The only negative I see is that it could attract discussion that belongs on the Git mailing list or in this GitHub repo, but we can avoid that by moderating all messages sent to the group. Usability beats vger/majordomo/mailman by far, IMO.

If I had a little money, time and a server, I would set up something like Scott Hanselman's [newsletter](http://www.hanselman.com/newsletter/) powered by [Sendy](http://sendy.co/). User friendly, full control and pretty cheap in the long run.

Given our target audience and our resources, I think the right choice would be Google Groups.

**Comment by tfnico** [comment]
@chriscool Somehow we managed to forget discussing this point the last few days! Please consider what I wrote in the last post, and tell me what you think. It would be nice to have something ready when we ship 2nd. ed.

**Comment by durdn** [comment]
@tfnico I agree that it would be great to have an email catcher ready for the 2nd edition. (Hi Thomas, good to reconnect here after Git Merge :)).

Personally I love MailChimp, for the usability primarily but also because it is setup exactly for the kind of broadcast workflow that the newsletter plans to be. We could start with their free tier and ask how they would feel to sponsor the initiative for free. Or maybe if you guys think it's relevant you could use a few dollars from the software conservancy budget to support the effort.

I am not familiar with the admin interface of Google Groups, would that allow for a broadcast only style newsletter? Indeed you wouldn't not want to transform it into yet another mailing list.

**Comment by tfnico** [comment]
@durdn Hey, great to have you join in here :)

I'm +1 on MailChimp if you're already familiar with it, and you're able to set it up in time for edition 2 (this weekend perhaps? ref #29). We should add instructions on how to subscribe on http://git.github.io/rev_news/rev_news.html .

With Google Groups I meant having a group where only one of us sends one email with every released edition. All other mails to the list would be blocked. This is pretty much the same as your average ANNOUNCE-list, see for example https://groups.google.com/forum/#!forum/scala-announce .

**Comment by durdn** [comment]
@tfnico So ok as a first step I created a gmail account gitrevnews [attt] gmail.com (will send the password privately to you and @chriscool ). And I created an account on Mailchimp too (username 'gitrevnews').

**Comment by chriscool** [comment]
@durdn I am ok with Mailchimp, thanks for taking care of this!

**Comment by tfnico** [comment]
Thanks to @durdn there is now a signup link on http://git.github.io/rev_news/rev_news.html

We'll see if we can make a more user-friendly sign-up form in the site itself later on.

**Comment by gitster** [comment]
rev_news/rev_news.html, "Subscribe" section has "all previous *episodes* on the archive page"; I think you would want to s/episodes/editions/, as you guys are using that word, perhaps?

**Comment by tfnico** [comment]
@gitster Fixed in https://github.com/git/git.github.io/commit/e35948174117795270055872f936eed487486ced. Thanks! I'm starting to worry we are taking too much of your time here ;)
