### ISSUE TITLE
rev_news: developer spotlight

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#33]
Thanks to @gitster for this idea.

We could highlight some Git contributor in each edition. Hopefully we can have the first already in ed. 2 (#29).

Some example questions:

* Who are you, and what do you do?
* What would you name your most important contribution to Git?
* What are you doing on the Git project these days, and why?
* If you could get a team of expert developers to work full time on something in Git for a full year, what would it be?
* If you could remove something from Git without worrying about backwards compatibility, what would it be?
* What is your favorite Git-related tool/library, outside of Git itself?

**Comment by chriscool** [comment]
I am ok with this idea and I like the questions, but I think we have enough articles for edition 2.
Let's keep this idea for later when we might have less material.
Though it's true that we could start sending emails to some developers.

I would ask "If you could change something from Git ..." instead of "If you could remove something from Git ..."

**Comment by tfnico** [comment]
> I would ask "If you could change something from Git ..." instead 
> of "If you could remove something from Git ..."

@chriscool I like that question, because framing something in a more destructive mindset can spur creativity. Some "provocative" questions can also focus the mind of both readers and interviewees. If you think it is too tabloid, I don't mind changing it.

**Comment by chriscool** [comment]
Ok let's keep "remove" then.
And maybe we can send the first emails after edition 2 is published.

**Comment by chriscool** [comment]
@gitster @tfnico I am continuing here the discussion started on issue #56 (Any comment about upcoming Git Rev News edition 3) about having GSoC students as developer spotlight stars.

@tfnico are you ok to start sending emails with the above questions so we can have one developer spotlight in edition 4, or do you prefer to wait or that someone else does it?

**Comment by tfnico** [comment]
@chriscool At the moment I'm swamped both with GitMinutes and Jekyll, so I would prefer if we could delegate this.

**Comment by chriscool** [comment]
@tfnico if you are still swamped I will send emails soon to hopefully have one developer spotlight in edition 4.

**Comment by tfnico** [comment]
@chriscool Sure, I'm as swamped as ever.

**Comment by chriscool** [comment]
Ok, I will try to take care of this for the next editions as I did in edition 7, so I think we can close this.
