### ISSUE TITLE
Improve Color Contrast

### ISSUE THREAD

**Issue by atilacamurca** [git/git.github.io#332]
I always have a hard time reading the Git Rev News because of the poor color contrast.

According to <https://webaim.org/resources/contrastchecker/?fcolor=6DC6DD&bcolor=ECEBE1>, the colors used fail to create a proper contrast even in large sizes.

If you change the blue to a darker vresion I would apreciate that.

**Comment by mjaix** [comment]
Hi Átila,

thanks for your suggestion.
I have played a tiny bit with colours, and I feel that 
https://webaim.org/resources/contrastchecker/?fcolor=007999&bcolor=F4F3ED
still looks blue-ish enough (albeit not as friendly as the original),
and at the same time leaves a gap towards the white background used
for quoting commands.
Would that contrast be good enough?
Better ideas are most welcome ...

Best regards,
Markus

**Comment by atilacamurca** [comment]
@mjaix this blue `#007999` is so much better.

PS.: I notice that the blue color from the git rev news that comes from email (`#6dc6dd`) is different than the one from the website (`#0388a6`). And the blue from email newsletter is far worse to read. So, my suggestion is to match the colors from both email and website with the one you suggest `#007999`.

![git-rev-news](https://user-images.githubusercontent.com/508624/50560659-c394e200-0ce1-11e9-8604-07b56ec32fec.png)

This is screen shot with one of the links with the new color - `#007999` Git Rev New Page link -, and the old ones `#6dc6dd`.

**Comment by mjaix** [comment]
Implemented via choosing a "compose your own" template in mailchimp,
resulting in template "Git Rev News v2.0.5".
Squashed efforts of #220 and #332.
Background is now "#f0efe7" except <code> snippets ("#fff"), and the blue links
have been changed to "007691" (intermediate step was full saturation "#0087ab").
The minimal contrast of the mail content should now be 4.5:1.

**Comment by mjaix** [comment]
Hi Átila, 
again thanks for your suggestion. Feel free to further comment after receiving the mail in the next few hours.
Best regards,
Markus
