### ISSUE TITLE
Have a stable URL that always points at the latest edition

### ISSUE THREAD

**Issue by gitster** [git/git.github.io#34]
I was updating the MaintNotes and wanted to advertise the rev-news, but I had to spell the current one like this:

There is a volunteer-run newsletter to serve our community
(http://git.github.io/rev_news/edition-1.html).  If you want to help
its publication, please contact Christian and/or Thomas.

which is way suboptimal.  By the time I send it the next time, edition-1 would be stale, and
http://git.github.io/rev_news/ will just give us a 404.

**Comment by peff** [comment]
Ideally we could just symlink `index.md` to `edition-1.md`, but unfortunately symlinks do not work at all in Jekyll mode (I have a hunch that they are omitted completely to avoid symlink-traversal issues).

I think you could also have a Jekyll "include" of the content into `index.md`. But unfortunately I think that that may require that the content live in the `_include` directory, and would mean the regular editions would then have to include their content manually. Sort of a pain.

Perhaps the best bet would be a redirect, which I think would look like #35. Though perhaps an index page for all of the rev-news editions would make more sense. I'll leave that up to the editorial staff.

**Comment by tfnico** [comment]
Jekyll offers a [range of permalink configurations](http://jekyllrb.com/docs/permalinks/). Oh, Peff just fixed as I was writing along here :+1:

**Comment by tfnico** [comment]
Once we've got a proper Jekyll blog up and running, we can use this URL for an index page like @peff suggested. Perhaps showing the latest 5 editions, or some archive listing.
