### ISSUE TITLE
--word-diff not reports removed blank line

### ISSUE THREAD

**Issue by kpeejp** [git/git.github.io#370]
"--word-diff" is very useful for me!
But never reports removed blank line.
eg.
    $ cat a.txt
    This is first line.
    This is second line.

    The third line is blank.

    $ git add a.txt && git commit -m 'Add a.txt'
    $ vi a.txt  # edit it
    $ cat a.txt
    This is first line.
    This is second line.
    The third line is blank.

    $ git diff --word-diff
    This is first line.
    This is second line.

    The third line is blank.

The third line is the same, and the diff-marker does not appear. I do not know what happened with this.
If the third line is modified...

    $cat a.txt
    This is first line.
    This is second line.
    This is third line.

    $ git diff --word-diff
    diff --git a/a b/a
    index a89575c..3d751e7 100644
    --- a/a
    +++ b/a
    @@ -1,4 +1,3 @@
    This is first.
    This is second.
    [-The third line-]{+This+} is [-blank.-]{+third line.+}

I still do not know that the blank line is gone.
I want to be displayed as follows.

    diff --git a/a b/a
    index a89575c..3d751e7 100644
    --- a/a
    +++ b/a
    @@ -1,4 +1,3 @@
    This is first.
    This is second.
    [--]
    [-The third line-]{+This+} is [-blank.-]{+third line.+}

This would be the best.

    diff --git a/a b/a
    index a89575c..3d751e7 100644
    --- a/a
    +++ b/a
    @@ -1,4 +1,3 @@
    This is first.
    This is second.[-
    -]
    [-The third line-]{+This+} is [-blank.-]{+third line.+}

Thank you.

**Comment by moy** [comment]
I think you want to report a bug it Git, but this is not the place to do so (this is the repo & issue tracker for the https://git.github.io/ website). Bugs are discussed on the Git mailing-list.
