### ISSUE TITLE
Have a look at Jekyll Now and Paper Now

### ISSUE THREAD

**Issue by chriscool** [git/git.github.io#39]
@tfnico as discussed IRL a few days ago ;-) we could have a look at:

https://github.com/PeerJ/paper-now

and:

http://www.jekyllnow.com/

**Comment by tfnico** [comment]
@chriscool Thanks for reminding me. Here are my thoughts:

Regarding Jekyll Now, this would've been a great way if we were starting from scratch. By now, we already have a number of URLs that have to be preserved, and I'm wondering if we're not better off simply tweaking what we've got to make it look nicer. Evolution over revolution, etc. Perhaps there is a bank of Jekyll theme CSS files somewhere we can simply slap on the current site to make it look pretty. I could be wrong about this, but I have a feeling it will cost some time to warp the old URLs into working in a new Jekyll Now instance. 

Regarding paper-now. I think the above points apply here too. Furthermore, paper-now seems made for academic article with attached figures and data, not really the same focus as a newsletter.

I could invest the time in doing a spike on either of these, but I tend towards thinking that tweaking vanilla Jekyll (slowly) into doing what we want is more worth our time. What do you think?

**Comment by chriscool** [comment]
@tfnico yeah I agree that we have to preserve URLs and I am ok with evolution over revolution.
But if we have time, it could be interesting to see how these projects are working because we might want to do some of the same things.

**Comment by tfnico** [comment]
I'll close this for now and get back to it when we are planning new features/redesign.
