### ISSUE TITLE
SOC 2020 Microprojects Link Doesnot Exist

### ISSUE THREAD

**Issue by jainpawan21** [git/git.github.io#419]
![Screenshot (55)](https://user-images.githubusercontent.com/39362422/75021473-7746cb80-54ba-11ea-8bbd-e89649627b38.png)
![Screenshot (57)_LI](https://user-images.githubusercontent.com/39362422/75021506-862d7e00-54ba-11ea-852f-58973021279c.jpg)

**Comment by chriscool** [comment]
Thanks for spotting this! We haven't created the file the link should point to yet, but we are going to do it soon.

In the meantime I might replace it with a link to: https://git.github.io/General-Microproject-Information/

**Comment by chriscool** [comment]
This should be fixed now. Please reopen if I missed some links.
