### ISSUE TITLE
Make it easier to read on mobile

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#43]
Some obvious points:

* The menu dominates above the content
* The fonts are way too small to be readable

**Comment by tfnico** [comment]
This is what it looks like on my Moto G:

![mobile screenshot](https://lh6.googleusercontent.com/Qm8jGO18sav7l08kf5-4Q_Q4F3pr48OKgyryyVyqT9SZkR8e4FQaXhu1y_J5y8tDEx8j_O4S=w1896-h849-rw)

**Comment by tfnico** [comment]
Here's what it looks like after @larsselstad's fix:

![mobile screenshot](http://i.imgur.com/Rb8t7DQ.png)

Much better!

**Comment by larsselstad** [comment]
I made a new PR which fixes the space to the right on the screen. #79
