### ISSUE TITLE
Add a page with hints about debugging Git 

### ISSUE THREAD

**Issue by phil-blain** [git/git.github.io#435]
Could start with:
https://github.com/gitgitgadget/git/pull/582#issuecomment-599845508
> Hi @ParthGala2k !
> 
> > Also I'm having trouble running the program on gdb, is there any reference for that?
> 
> The [CodingGuidelines document](https://github.com/git/git/blob/6c85aac65fb455af85745130ce35ddae4678db84/Documentation/CodingGuidelines#L435) also has some guidance for using the system-installed GDB.
> 
> If you compiled GDB yourself you will need to invoke it like this:
> 
> ```
> GIT_DEBUGGER="/path/to/gdb --args" ./bin-wrappers/git <command> <args...>
> ```
> 
> I you are on macOS and want to use LLDB, that would be:
> 
> ```
> GIT_DEBUGGER="lldb --" ./bin-wrappers/git <command> <args...>
> ```
> 
> Sometimes Git command spawn other Git commands under the hood, using fork+exec. You will recognize this by a call to either [`run_command`](https://github.com/git/git/blob/bc7a3d4dc04dd719e7c8c35ebd7a6e6651c5c5b6/run-command.c#L1003) or more rarely directly to [`start_command`](https://github.com/git/git/blob/bc7a3d4dc04dd719e7c8c35ebd7a6e6651c5c5b6/run-command.c#L667).
> 
> If the code your are trying to debug is in an instance of git spawned (fork+exec) by the main git process, you will need to use the [`set detach-on-fork off` option in GDB](https://sourceware.org/gdb/onlinedocs/gdb/Forks.html), which works on Linux but not on macOS (I don't know about anything about Windows). I had success doing that on Ubuntu 17.10 using a self-compiled GDB 8.3.1, but not with the system-installed GDB 7.1.2.
> 
> Another option is to put a call to `sleep()` just after the [fork in `start_command`](https://github.com/git/git/blob/bc7a3d4dc04dd719e7c8c35ebd7a6e6651c5c5b6/run-command.c#L779), then open another instance of GDB and attach to the new process, e.g. with
> 
> ```
> gdb -p $(pgrep -n git)
> ```
> 
> Then you can control both instances independently.
> 
> Addendum: there is also some interesting guidelines on the old wiki, that might still be useful for debugging tests: https://git.wiki.kernel.org/index.php/What_to_do_when_a_test_fails

maybe also add pointers to configure VScode for debugging.

also : https://github.com/gitgitgadget/git/pull/582#issuecomment-608091702

also of interest: https://github.com/git-for-windows/git/wiki/Debugging-Git

**Comment by chriscool** [comment]
You are welcome to start such a page! What is in your above comment is a good starting point, so I encourage you to contribute it!

**Comment by phil-blain** [comment]
thanks @chriscool. I might get to this some day. I guess another question is does it make sense to put some of that info in git.git somewhere...

**Comment by chriscool** [comment]
I started something, see:

- https://git.github.io/Hacking-Git/
- https://github.com/git/git.github.io/blob/master/Hacking-Git.md

**Comment by chriscool** [comment]
@phil-blain feel free to contribute to the above page :-)

**Comment by chriscool** [comment]
Let's close this for now and maybe open more specific issues to improve the above page.
