### ISSUE TITLE
Integrating Matheus' "First steps contributing to Git" tutorial

### ISSUE THREAD

**Issue by phil-blain** [git/git.github.io#436]
Hi @matheustavares !

When I was starting out with Git I found your tutorial https://matheustavares.gitlab.io/posts/first-steps-contributing-to-git to be immensely helpful. 

A lot of things you mention are not found in the ["My First Contribution"](https://git-scm.com/docs/MyFirstContribution) tutorial (ex. the weekly standups, the patchwork server, etc.)

What would you think about adding it as a new page to this site ? it would give it a little more visibility, maybe :) 

Cheers!

**Comment by matheustavares** [comment]
Hi, @phil-blain 

> When I was starting out with Git I found your tutorial https://matheustavares.gitlab.io/posts/first-steps-contributing-to-git to be immensely helpful.

I'm glad to hear that! :)

> What would you think about adding it as a new page to this site ? it would give it a little more visibility, maybe :)

Yeah, I think that would be really nice. Perhaps, to avoid duplicating the information, we could add a link to the tutorial? I think this could go at https://git.github.io/General-Microproject-Information/, in the paragraph that mentions `Documentation/SubmittingPatches` and the contribution process. (A link to `Documentation/MyFirstContribution` could also be added here.)

(Another place we could add a link, if folks like the idea, is at https://git-scm.com/community.)

**Comment by matheustavares** [comment]
Nevertheless, it shouldn't be hard to re-post the tutorial page, as it is also written in markdown, with jekyll :)

Here is the source code for it: https://gitlab.com/MatheusTavares/matheustavares.gitlab.io/-/blob/master/_posts/2019-09-02-first-steps-contributing-to-git.md  (Note that it does use some custom CSS classes, but in very few places)

**Comment by matheustavares** [comment]
Nevertheless, it shouldn't be hard to re-post the tutorial page, as it is also written in markdown, with jekyll.

Here is the source code for it: https://gitlab.com/MatheusTavares/matheustavares.gitlab.io/-/blob/master/_posts/2019-09-02-first-steps-contributing-to-git.md (Note that it does use some custom CSS classes, but in very few places)

**Comment by chriscool** [comment]
Thanks @matheustavares and @phil-blain! For now I started the following:

    https://git.github.io/Hacking-Git/
    https://github.com/git/git.github.io/blob/master/Hacking-Git.md

Feel free to contribute!

**Comment by chriscool** [comment]
See also https://github.com/git/git.github.io/issues/435

**Comment by matheustavares** [comment]
Great, thanks @chriscool !

**Comment by phil-blain** [comment]
Super, thanks @chriscool. I think a list of ressources like this is a good idea.

**Comment by chriscool** [comment]
Ok, I think I can close this.
