### ISSUE TITLE
A crazy thought : people can choose add .git to their words.

### ISSUE THREAD

**Issue by StevenJokes** [git/git.github.io#445]
I don't know how to give advice to git. So I just tell you guys the idea here.

---

My thought is that people can add their commits easily on every words, pictures, videos and etc.
And when we choose to copy the words, the commits will follow at the same time.
Then we can easily track where the original words came from and protect authors' copyright.
It is meaningful for every writers, coders, and every creaters on the web.
It is useful to avoid online sensation and plagiarism。

**Comment by chriscool** [comment]
Technically I think this could be possible using a DHT (distributed hash table). Commits could be associated to some content by being associated with the hash of the content in the DHT. Maybe something like IPFS (https://ipfs.io/) could help implementing that.

Now I am not sure it would protect authors much, as it's easy to modify the content a bit and then to add one's own new commits to the new content. It could perhaps prove that the original content already had some commits when the new content was added to the DHT, but that can already be done by registering content in a blockchain. For example there is already: https://creaproject.io/crea-en/.

So I am not sure what the practical advantage would be.

**Comment by StevenJokes** [comment]
emmm.. Maybe using it can track the original source as old as possible?

**Comment by chriscool** [comment]
> emmm.. Maybe using it can track the original source as old as possible?

Yeah, but maybe using https://creaproject.io/crea-en/ or other similar projects about registering content in a blockchain (like https://content-blockchain.org/ for example) can also track the original source as old as possible. I think it all depends on how soon such a system is used, which depends on how popular it is and which other features it provides.

**Comment by StevenJokes** [comment]
Thanks anyway. I'll try next time!
