### ISSUE TITLE
Only show excerpts in Rev News archive page

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#45]
Once we have multiple editions, the archive page will be too long.

**Comment by chriscool** [comment]
Yeah and maybe we can avoid showing stuff like:

```
news
05 Apr 2015 chriscool avatar chriscool 
```

near the top of the archive page too.

**Comment by tfnico** [comment]
As there is no easy way of making nice excerpts easily [1], I'll close this for now as the archive page is good enough for now.

[1] http://jekyllrb.com/docs/posts/#post-excerpts

**Comment by chriscool** [comment]
@tfnico the archive page page looks really nice now! Thanks!
