### ISSUE TITLE
git format-patch lost the last part when branch merge

### ISSUE THREAD

**Issue by wangyugui** [git/git.github.io#480]
Hi,

git format-patch lost the last part when branch merge.

Here is an example.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Merge tag 'for-5.12/block-2021-02-17' of git://git.kernel.dk/linux-block

1, from the web interface,
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs?id=582cd91f69de8e44857cb610ebca661dac8656b7

the last part 'diff --git a/fs/btrfs/zoned.c b/fs/btrfs/zoned.c' can be confirmed.

2,  but from ' commit | 582cd91f69de8e44857cb610ebca661dac8656b7 (patch)' of this web page,
the last part 'diff --git a/fs/btrfs/zoned.c b/fs/btrfs/zoned.c' is not in the patch file.

3,  git format-patch 4f016a316f22.. fs/btrfs/ will not output 'diff --git a/fs/btrfs/zoned.c b/fs/btrfs/zoned.c' too.

Best Regards

**Comment by wangyugui** [comment]
git version: 2.27.0 in rhel8
git version: 2.30.1

**Comment by chriscool** [comment]
Issues with Git itself should be discussed on the Git mailing list, see: https://git-scm.com/community not in this project. 

This project is only for the Git developer pages at: https://git.github.io/
