### ISSUE TITLE
Mentioning MyFirstContribution in General-Microproject-Information

### ISSUE THREAD

**Issue by sivaraam** [git/git.github.io#485]
In the [General-Microproject-Information](https://git.github.io/General-Microproject-Information/) page, we have the following paragraph:

> Read about the process for submitting patches to Git: this is described in `Documentation/SubmittingPatches`.

I get the feeling that it would be worthwhile to mention `MyFirstContribution` there too. Possibly as follows:

> Read about the process for submitting patches to Git: this is described in `Documentation/SubmittingPatches`. For a more detailed step-by-step guide could be found in [`Documentation/MyFirstContribution.txt`](https://git-scm.com/docs/MyFirstContribution).

What do others think? If that doesn't seem like an appropriate place, we could at least mention it somewhere else in that document.

**Comment by chriscool** [comment]
Yeah, we could also link to https://git.github.io/Hacking-Git/ which has a lot of links about many topics.
