### ISSUE TITLE
RevNews #2: do not forget to remove "Support" if it stays empty

### ISSUE THREAD

**Issue by gitster** [git/git.github.io#51]
As this issue is an "special edition", it is perfectly OK if there were nothing noteworthy to report in the "Support" section, but if that will be the end result (we may not know yet), please remove the section heading before the empty section (this comment applies to any other sections, but I think everything other than "Support" has some contents already).

**Comment by chriscool** [comment]
@gitster sorry I just saw this issue now.
I will remove empty sections in the next editions.
Thanks for reporting.

**Comment by chriscool** [comment]
@gitster I just removed it from edition 2.

**Comment by gitster** [comment]
May I suggest that you might want to start your empty template with these empty headers commented out, and uncomment them only when you add some contents? That way you are likely not to repeat this mistake.

**Comment by chriscool** [comment]
@gitster ok, I will see if I can do that.
Thanks for the suggestion.
