### ISSUE TITLE
The file name is not sensitive to case, so it is very troublesome to modify the file name

### ISSUE THREAD

**Issue by hai2007** [git/git.github.io#512]
For example, I used to have a file：

``` MyFile.h```

Now, I want to change the name to：

```myFile.h```

But after I submit the code to the server, the name of the server is still ```MyFile.h```

**Comment by chriscool** [comment]
This is not the place to discuss Git's behavior. This repo is only about the https://git.github.io/ web pages.

Please take a look at: https:// git-scm.com/community

**Comment by hai2007** [comment]
ok
