### ISSUE TITLE
Please provide a RSS feed

### ISSUE THREAD

**Issue by thomasdeniau** [git/git.github.io#53]
It would be great to get new editions of the Git Rev newsletter through my RSS reader.

**Comment by thomasdeniau** [comment]
Sorry, just noticed this was issue https://github.com/git/git.github.io/issues/30

**Comment by tfnico** [comment]
Yeah, I'll agree it's not so easy to see/find the link. We're working on the design/layout of the site, and should at some point have an RSS icon in the header or something.
