### ISSUE TITLE
Remove the git-for-each-ref microproject from GSoC microproject list?

### ISSUE THREAD

**Issue by ffyuanda** [git/git.github.io#546]
@sivaraam @chriscool 

Hi people,

Here is Shaoxuan Yuan. And I'm highly interested in participating in GSoC 2022 at git :-)

As per the response by @gitster [here](https://lore.kernel.org/git/xmqqzgnbf8w6.fsf@gitster.g/), probably the [idea ](https://git.github.io/SoC-2022-Microprojects/#add-no-sort-option-for-git-for-each-ref) should be removed or revised?

**Comment by chriscool** [comment]
@ffyuanda thanks! I removed it in 1867eba7856360bea9ba83a4c0317c051ec9837b.
