### ISSUE TITLE
Advertise Git Review Club in Git Rev News?

### ISSUE THREAD

**Issue by steadmon** [git/git.github.io#552]
Hi, I was wondering if we could get a standing advertisement for the [Git Review Club](https://lore.kernel.org/git/Yfl1%2FZN%2FtaYwfGD0@google.com/) in each future issue of Git Rev News?

It could just be a small blurb about how we meet up (bi-weekly Wednesdays Pacific-time) to learn how to be effective reviewers, a link to the announcement above, and a note that anyone interested should contact me at steadmon@google.com.

Thanks!

**Comment by chriscool** [comment]
Yeah, I am ok with advertising for it in the way you suggest in the next editions.

**Comment by steadmon** [comment]
Hi Chris, sorry I didn't see your reply earlier. It did happen, but I am trying to avoid causing too much traffic on the mailing listin case folks feel it's too spammy. The next meeting is on the 16th if you're interested :)

**Comment by chriscool** [comment]
Hi Josh, yeah I am interested in talking about the past and future Git Review Club meetings in Git Rev News or making it easy to see when they happen.

So if for example you add them to https://tinyurl.com/gitCal, then I am fine with mentioning that in the next Git Rev News edition. If you prefer to give us the dates and subjects (as much as possible in advance for the future meetings), then I am fine with listing them.

**Comment by steadmon** [comment]
Hi Chris, sorry again for the late reply. I just got write-access to git-cal, so I'll start updating the event entries with each session's topic. The meeting notes are also public, and can be found here: https://docs.google.com/document/d/14L8BAumGTpsXpjDY8VzZ4rRtpAjuGrFSRqn3stCuS_w/edit#heading=h.ikdxqrr02bs

**Comment by chriscool** [comment]
Hi Josh,
I am still not sure how to best advertise the Review Club in Git Rev News. Anyway I just improved the https:// git.github.io/Hacking-Git/ page, and added a link to https://lore.kernel.org/git/?q=s%3A%22Review+Club%22 there. I also mentioned that Review Club meetings are announced on git-cal. I hope this helps!

**Comment by chriscool** [comment]
I think the Review Club is not running any more, so we can close this.
