### ISSUE TITLE
Change point of contact for access?

### ISSUE THREAD

**Issue by sivaraam** [git/git.github.io#553]
Our README has the following sentence.

> If you want push access, contact peff@peff.net and provide your GitHub username.

Since Peff is on a [break from Git](https://public-inbox.org/git/YboaAe4LWySOoAe7@coredump.intra.peff.net/) now, I wonder if we need to change the point of contact to a different person? If yes, who would be the appropriate person now? @chriscool ?

**Comment by ttaylorr** [comment]
> @ttaylorr could you confirm?

I thought so, too. Though when checking, I found that I don't have administrator privileges for this repo, so I'd be unable to add anybody to the list of allowed pushers even if I wanted to.

I don't mind being the point of contact here, but an existing admin would need to grant me access. @chriscool are you an admin on this repo?

**Comment by chriscool** [comment]
Yeah, I am actually an admin of this repo. Nice! I don't remember when I was made admin though.

@ttaylorr I added you to the git/@web team which has write access to the repo. I think I should also give you admin rights, so that I am not the only one to have them.

@sivaraam yeah, as I am admin, I think it's best for me to be the point of contact on our README.

**Comment by ttaylorr** [comment]
> @ttaylorr I added you to the git/@web team which has write access to the repo. I think I should also give you admin rights, so that I am not the only one to have them.

Thanks. I had write access before when Peff added me, but consolidating it via the `@git/web` team is the right way to do it. I don't mind being an admin as well, and it's probably good for there to be more than one of us. I'm fine if you're the point of contact, or if I am, or if both of us are ;).

**Comment by sivaraam** [comment]
> Yeah, I am actually an admin of this repo. Nice! I don't remember when I was made admin though.

I think that might've been Peff's doing per [this comment](https://github.com/git/git.github.io/issues/434#issuecomment-643979790). I'm not sure if you're referring to something else, though.

>  I'm fine if you're the point of contact, or if I am, or if both of us are ;).

That's nice. I feel that mentioning both of you in the README would be a good thing to do. I can open a PR for that. I'm a little iffy about whether you've been given admin rights, Taylor. If Christian could confirm that he's given it, I'll mention both of you in the README.

**Comment by chriscool** [comment]
> I think that might've been Peff's doing per https://github.com/git/git.github.io/issues/434#issuecomment-643979790. I'm not sure if you're referring to something else, though.

@sivaraam right! Not sure why I don't remember it.

> I'm a little iffy about whether you've been given admin rights, Taylor. If Christian could confirm that he's given it, I'll mention both of you in the README.

Yeah, I just gave @ttaylorr the admin right. And yeah, it's a good idea to mention both of us in the README.

Thanks!
