### ISSUE TITLE
Adjusting the SoC Ideas list as per GSoC requirement

### ISSUE THREAD

**Issue by sivaraam** [git/git.github.io#561]
GSoC mailed Org Admins stating that the ideas list of orgs need have some crucial information. I have tweaked the ideas list to adjust to their requirement to an extent. We might still need to some add some more information to it. Here's the list of things that GSoC requested:

a) a project title/description 
b) more detailed description of the project (2-5+ sentences) 
c) expected outcomes 
d) skills required/preferred
e) possible mentors 
f) expected size of project (175 or 350 hour) 
g) an easy, medium or hard difficulty rating of each project.

We have most of these except for maybe c and g. It would nice if mentors of corresponding projects could check if each project has all the required information. 

cc @chriscool @harry-hov @derrickstolee @vdye @ttaylorr

**Comment by ttaylorr** [comment]
@sivaraam Thanks for the information. I took a look over my SoC project, and it has all of the information that GSoC requested. Let me know if you want me to add anything else.

**Comment by derrickstolee** [comment]
I would rate sparse index integrations as medium difficulty. I think the outcomes are pretty clear from the description.

**Comment by sivaraam** [comment]
> I took a look over my SoC project, and it has all of the information that GSoC requested. Let me know if you want me to add anything else.

Thanks for the quick response!

I think we might need to explicitly mention the project difficulty (Easy / Medium / Hard). I've tentatively mentioned the difficulty as "Medium" on reading the project description. Let me know in case that needs to be changed.

Also, on reading the description I realized that the idea has the potential to be a 350 hours project too. So, I mentioned the "Expected Project Size" to be 175 hours or 350 hours. Let me know if that's fine.



> I would rate sparse index integrations as medium difficulty. I think the outcomes are pretty clear from the description.

Mentioned the difficulty in the ideas list. Thanks for the quick response!

**Comment by ttaylorr** [comment]
> I think we might need to explicitly mention the project difficulty (Easy / Medium / Hard). I've tentatively mentioned the difficulty as "Medium" on reading the project description. Let me know in case that needs to be changed.
> 
> Also, on reading the description I realized that the idea has the potential to be a 350 hours project too. So, I mentioned the "Expected Project Size" to be 175 hours or 350 hours. Let me know if that's fine.
> 
> >

Both sound fine to me, thanks!

**Comment by harry-hov** [comment]
> I've tentatively mentioned the difficulty as "Medium" for the "Unify ref-filter" idea too. Hope that's fine. cc @chriscool @harry-hov

Yep. It's "Medium". I'm not sure how to calculate "Expected Project Size" in terms of 175 hours or 350 hours. @chriscool?

**Comment by chriscool** [comment]
Yeah, I am ok with "Medium" for difficulty and "175 hours or 350 hours" for expected project size.

**Comment by chriscool** [comment]
Thanks @sivaraam for your tentative changes!

**Comment by chriscool** [comment]
About "Expected project size" I think we could probably have "175 hours or 350 hours" everywhere.

**Comment by sivaraam** [comment]
> About "Expected project size" I think we could probably have "175 hours or 350 hours" everywhere.

Makes sense. I've changed both projects to mention that they could 175 hours or 350 hours (cf. ec4c2eaf2e2a68f6c84c18ef94497a3bf03c650b). Let me know in case you have a different opinion for the "Sprase Index Integrations" project @derrickstolee 

One other thing, I thought of mentioning regarding the project timeline. GSoC allows the GSoC contributor (applicant) to write a proposal with a particular timeline in mind. Mentors could work with GSoC contributor during the summer to adjust the timeline if required. _But_ note well that, GSoC does not allow to switch a project to a larger project from a medium sized project once slots have been assigned. So, I suppose it might be good to roughly plan the timeline for a project during the application period itself. This might avoid potential issues during the contribution period.

_Note_: The above information is based on details shared by Stephanie about the changes to GSoC 2022 program in the GSoC mentors list.

**Comment by sivaraam** [comment]
Closing this as it's done
