### ISSUE TITLE
Add analytics (for Rev News)

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#57]
Some statistics would be a nice motivation tool.

**Comment by tfnico** [comment]
@chriscool FYI, I just pushed this.

**Comment by chriscool** [comment]
Yeah, I got an email. Thanks!

**Comment by tfnico** [comment]
Analytics are starting to trickle in now, so it's working.

**Comment by tfnico** [comment]
@chriscool I just checked the analytics for the first time in a while now. Looks pretty stable on around 900 visitors per month. In March there was a super-boost with hundreds of sessions per day - perhaps that was when we were linked from LWN (?).

If I am reading the analytics correctly, it appears that only the first 50 or so stay on the page for more than a minute. It could be that this is distorted due to desktop browsers having adblockers and other stuff that disable the analytics, not sure.

**Comment by chriscool** [comment]
Ok thanks for the report @tfnico !
