### ISSUE TITLE
Include development info in README?

### ISSUE THREAD

**Issue by sivaraam** [git/git.github.io#610]
Previously the repo's README used to be a link to [_includes/README.md](https://github.com/git/git.github.io/blob/master/_includes/README.md). It's now a normal file with some information about the site. It is nice for [the landing page](https://git.github.io/).

Though, now it lacks basic instructions that would help someone to know how to spin up the site for development locally. Would it be helpful if we include it in the repo's README in some way?

**Comment by chriscool** [comment]
Thanks @sivaraam for noticing this and opening this issue!

I agree it would be helpful to include the basic instructions that would help someone to know how to spin up the site for development locally!

**Comment by chriscool** [comment]
@utkarsh006 I think we should have been a bit more careful with https://github.com/git/git.github.io/pull/606

**Comment by sivaraam** [comment]
I just realized the landing page of git.github.io is actually present in [index.md](https://github.com/git/git.github.io/blob/master/index.md) in the root of the repo. The README in the root of the repo also seems to be based on the content in it.

I'm wondering if we should just make the README to point to _includes/README like it used to given that it served us well all this while. If we feel anything from the new README worth keeping (the contributor list?), we could think of moving it over to _includes/README.

Let me know your thoughts.

**Comment by chriscool** [comment]
@sivaraam sorry for not replying earlier.

I agree that it would be nice to have basic instructions to know how to spin up the site for development locally. Could we put them in the README.md?

Would it work to then remove both _includes/README.md and index.md altogether and keep only README.md? Which pages were including or linking to _includes/README.md, and what kind of link it was? A symbolic link?

It looks to me like only the "about" page is currently including README.md. Also I think symbolic links are not very friendly for Windows users, so it would be nice if we wouldn't use one.

So another possibility might be to have both README.md and about.md include _includes/README.md with the latter having the same content as the current README.md and the basic instructions to spin up the site.

What do you think?

**Comment by sivaraam** [comment]
> So another possibility might be to have both README.md and about.md include _includes/README.md with the latter having the same content as the current README.md and the basic instructions to spin up the site.

I tried to do this, Christian. It seems we can't have a single README which unifies the content for root and the index page of the site. The badge at the end and the contributor list don't seem to render well via Jekyll. So, I've tried to keep them separate (cloning common portions). Let me know if that's fine.
