### ISSUE TITLE
 cannot stat template FFft.txt

### ISSUE THREAD

**Issue by CodingJzy** [git/git.github.io#637]
![image](https://user-images.githubusercontent.com/44855157/227855948-b8e4ae88-1590-4681-9acc-f81c71f87601.png)

hello, when i clone repo，display the error ,i find the dir not found, and  the sec application display 

![image](https://user-images.githubusercontent.com/44855157/227856135-80eec650-da3b-4e77-8435-c444ce4216cd.png)

**Comment by jnareb** [comment]
This is repository for Git Developer Pages (https://git.github.io/), not for Git for Windows. Please post your bug report to the correct forum.
