### ISSUE TITLE
_posts/YYYY-MM-DD-edition-N.markdown vs rev_news/edition-N.md???

### ISSUE THREAD

**Issue by gitster** [git/git.github.io#64]
I know we have some workaround for the first edition's URL, but do we need to keep rev_news/edition-N.md for N > 1?

**Comment by tfnico** [comment]
Already noted under https://github.com/git/git.github.io/issues/56#issuecomment-101715138

**Comment by chriscool** [comment]
Ok, yeah we can remove edition-2.md and edition-3.md.

**Comment by gitster** [comment]
@tfnico Thanks.
