### ISSUE TITLE
Ask candidates to mention preferred project size in application

### ISSUE THREAD

**Issue by sivaraam** [git/git.github.io#642]
For GSoC, there are two possible project sizes Medium (175 hours) and Large (350 hours). We specify the possible project size in our [ideas page](https://git.github.io/SoC-2023-Ideas/) but we don't ask candidates to mention this information in [our application](https://git.github.io/General-Application-Information/#application-required). 

It is better to require this information in the application itself. This helps us verify that the student chooses a project size which we are comfortable with.

I suppose the following is the appropriate place in order to include this information: https://git.github.io/General-Application-Information/#application-required

Let me know if there's a better place.

**Comment by chriscool** [comment]
@sivaraam Yeah, I think it's the right place. If you go for it, don't hesitate to put it in bold style to make it stand out.

Thanks for creating this issue by the way! I think it might avoid confusion in the future.

**Comment by sivaraam** [comment]
On a side note, we should likely also highlight the current set of Org Admins somewhere (may be [Mentoring guide](https://git.github.io/Mentoring-Program-Guide/) / [Ideas page](https://git.github.io/SoC-2023-Ideas/) ?). This might help the students identify the Org Admins easily in case they need to reach out to them at some point of time.

**Comment by chriscool** [comment]
@sivaraam I would hope the GSoC website could help contributors find the Org Admins and reach out to them. Also I am not sure in which case Google suggests them to reach out to Org Admin instead of mentors or Google people. But if they indeed suggest that and don't make it easy to do so, yeah we could make it easy in some way. Maybe that could be part of another issue though.

**Comment by chriscool** [comment]
@sivaraam This should be fixed in a23578ba4d02137623eff3e0dfc8d3c5c98c2616. Also in a152047c934a0c3ea9d4dcec80ab6673ab55d665 I have added information about people who could be useful to contributors.

Let me know if you think we can close this. Thanks!

**Comment by sivaraam** [comment]
Thanks for the change, Christian. We could close this one 👍🏼
