### ISSUE TITLE
rev_news: twitter

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#66]
Some readers probably prefer "subscribing" by following on Twitter (atleast my podcast gathered a few hundred followers there). Who's for opening a @gitrevnews Twitter account? (as in: I'll do it unless there are objections)

cc @durdn @chriscool

**Comment by chriscool** [comment]
Yeah no problem, thanks for doing it!

**Comment by durdn** [comment]
Go ahead Thomas, great idea.

**Comment by chriscool** [comment]
@tfnico I saw that you announced the last edition using your own twitter account. Maybe that's even better than opening a @gitrevnews Twitter account, as you already have hundreds of follower, and we should just say somewhere that people should just follow you if they want to be notified by following on Twitter?

**Comment by tfnico** [comment]
@chriscool Yeah, I've been using my own account up until we get a @gitrevnews account. From then on, I'll start retweeting the announcement there instead. Just need some more time :P

**Comment by gitster** [comment]
Has this issue now been resolved, since we found a volunteer? Can we close it?

**Comment by chriscool** [comment]
I am ok to close it. What do you think @tfnico?

**Comment by tfnico** [comment]
Sure. Sorry I still didn't find the time to actually set up the account and
start tweeting yet.
On May 14, 2016 09:53, "Christian Couder" <notifications@github.com> wrote:

I am ok to close it. What do you think @tfnico <https://github.com/tfnico>?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/git/git.github.io/issues/66#issuecomment-219206863>

**Comment by chriscool** [comment]
Ok, let's close it anyway.
