### ISSUE TITLE
API to fecth approvers from a PR

### ISSUE THREAD

**Issue by ritiksethi21** [git/git.github.io#730]
Hi Team, is there any API to fetch the approvers for a PR ?

I came across https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-reviews-for-a-pull-request , but this doesn't give me list of only approvers and lets say:

* A user 'A' approved the PR, then suggested some reviews on the same too.
* This API will show the 'A' name in approvers too, which is not right.

Is there any git API which we can leverage to find approver's list or maybe some other way of fetching the valid approvers for a PR ?

**Comment by chriscool** [comment]
We are the "Git Developer page project" with the goal of helping people with Git development. We are not part of the GitHub team and cannot provide support related to GitHub. Please try to contact GitHub support in a different way.
