### ISSUE TITLE
Git Rev News #5

### ISSUE THREAD

**Issue by gitster** [git/git.github.io#76]
Please open the new issue ;-)

**Comment by gitster** [comment]
I'm collecting review-threads-one-liner summary for reasons other than contributing to the newsletter anyway, so I'll dump them from time to time here to see if any of them is of interest to the editors.

Here is my dump for the first week of 2015/06.

* "git format-patch --ignore-if-in-upstream A..B" [fix](http://thread.gmane.org/gmane.comp.version-control.git/270345/focus=270445) when A and B are not commits.
* Recent "git repack" triggered unnecessary [warnings](http://thread.gmane.org/gmane.comp.version-control.git/270378/focus=270421).
* Allowing "git bisect" to be used in "fix hunting" [more easily by avoiding value-laden good/bad](http://thread.gmane.org/gmane.comp.version-control.git/270754/focus=270792).
* Make "git status" aware of the [sequencer status](http://thread.gmane.org/gmane.comp.version-control.git/270743/focus=270861).
* Make "git rebase -i" instruction sheet [customizable](http://thread.gmane.org/gmane.comp.version-control.git/270872/focus=270876).

**Comment by chriscool** [comment]
@gitster thanks for the remainder. The new issue is there:

https://github.com/git/git.github.io/issues/77

The empty draft there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-5.md

**Comment by gitster** [comment]
My dump for 06/08-06/14

# Reviews

* "git bisect [new/old](http://thread.gmane.org/gmane.comp.version-control.git/271127/focus=271128)"
* reporting [warning](http://thread.gmane.org/gmane.comp.version-control.git/270952/focus=271134) when charset conversion did not happen due to iconv compiled out.
* Issues in "git am --abort" and other commands when applying a patch to [an unborn branch](http://thread.gmane.org/gmane.comp.version-control.git/270915/focus=271122).
* Issues in "git am" to apply [foreign SCM patches](http://thread.gmane.org/gmane.comp.version-control.git/271053/focus=271119).
* $branch^{/!-<pattern>} syntax to name [a commit that does not match the pattern](http://thread.gmane.org/gmane.comp.version-control.git/270896/focus=271071).
* making the instruction sheet given by "git rebase -i" [customizable](http://thread.gmane.org/gmane.comp.version-control.git/271131).
* enriching the output of [git status](http://thread.gmane.org/gmane.comp.version-control.git/271184/focus=271221) with ongoing "git rebase -i" state information.
* better modularization of [ref transactions](http://thread.gmane.org/gmane.comp.version-control.git/271017/focus=271224)
* tcsh completion support [fix](http://thread.gmane.org/gmane.comp.version-control.git/271205/focus=271228) under "set noclobber"
* [GSoC project](http://thread.gmane.org/gmane.comp.version-control.git/270942/focus=271232) to unify listing of selected refs by for-each-ref, tag and branch.
* [GSoC project](http://thread.gmane.org/gmane.comp.version-control.git/270639/focus=271272) to reimplement "git pull" in C.
* Updating documentation of [git checkout](http://thread.gmane.org/gmane.comp.version-control.git/271124/focus=271295) to clarify "checking out pristine contents out of index or tree" operation is destructive by design.
* Teaching git send-email to [expand aliases in output](http://thread.gmane.org/gmane.comp.version-control.git/271225/focus=271299) from --cccmd etc. 
* Introduce [tempfile API](http://thread.gmane.org/gmane.comp.version-control.git/270998/focus=271331) and build lockfile API on top





# Reports

* What's cooking (2015/06 [#03](http://article.gmane.org/gmane.comp.version-control.git/271366))

**Comment by gitster** [comment]
My dump for 06/15-06/21

# Reviews

* Handful of documentation updates.

* ["git bisect terms old new"](http://thread.gmane.org/gmane.comp.version-control.git/271343/focus=271687) to unconfuse users when the bisection operation is not finding a regression (i.e. when "used to be GOOD now it is BAD" does not work well).
* GSoC ["git am in C"](http://thread.gmane.org/gmane.comp.version-control.git/271381/focus=271694) and ["git pull in C"](http://thread.gmane.org/gmane.comp.version-control.git/271967/focus=272164).
* GSoC [unify the listing operations in "git for-each-ref", "branch" and "tag"](http://thread.gmane.org/gmane.comp.version-control.git/271563/focus=271706).
* Tidy up reference initialization in ["git clone"](http://thread.gmane.org/gmane.comp.version-control.git/271552/focus=271707)
* [Logging](http://thread.gmane.org/gmane.comp.version-control.git/271451/focus=271777) fetched packfile generated by a suspect server. This is Augie's itch/seed solved in a different way by Peff.
* "git format-patch" learns [format.outputDirectory](http://thread.gmane.org/gmane.comp.version-control.git/271963/focus=272083) configuration.
* "git stash apply" [had a regression not in so distant past](http://thread.gmane.org/gmane.comp.version-control.git/270809/focus=271693)
* Allowing ["git fsck" errors to be demoted to warnings](http://thread.gmane.org/gmane.comp.version-control.git/261053/focus=272171)



# Releases

* [Git 2.4.4](http://thread.gmane.org/gmane.linux.kernel/1977862)

# Reports

* What's cooking (2015/06 [#04](http://thread.gmane.org/gmane.comp.version-control.git/271803))

**Comment by chriscool** [comment]
@gitster I am closing this, as the 5th edition has been pusblished some time ago.
