### ISSUE TITLE
Any comment about upcoming Git Rev News edition 7

### ISSUE THREAD

**Issue by tfnico** [git/git.github.io#94]
A currently mostly empty draft is there:

https://github.com/git/git.github.io/blob/master/rev_news/drafts/edition-7.md

Feel free to comment in this issue, or to use the edit button (that looks like a pen) to edit and create a pull request with the changes you would like.

Thanks!

cc @chriscool @durdn @gitster

**Comment by chriscool** [comment]
@tfnico @durdn thanks again for taking care of edition 6.
Now let's plan to publish edition 7 on Wednesday September 9!

**Comment by tfnico** [comment]
:+1:

**Comment by tfnico** [comment]
@chriscool @durdn my links and releases for this edition are pushed.

**Comment by chriscool** [comment]
Thanks @tfnico!

**Comment by chriscool** [comment]
Closing this as the edition has been published and it looks like there are no issues.
